/*
 * This file was automatically generated by EvoSuite
 * Mon May 02 10:28:37 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution_50_ESTest extends Solution_50_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution_50 solution_50_0 = new Solution_50();
      int int0 = solution_50_0.maxConsecutiveAnswers("pEf_*J;T[])gcUiU", 4054);
      assertEquals(16, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution_50 solution_50_0 = new Solution_50();
      int int0 = solution_50_0.maxConsecutiveChar("Solution_50", 0, ']');
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution_50 solution_50_0 = new Solution_50();
      int int0 = solution_50_0.maxConsecutiveAnswers("", (-1));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution_50 solution_50_0 = new Solution_50();
      // Undeclared exception!
      try { 
        solution_50_0.maxConsecutiveChar("pEf_*J;T[])gcUiU", (-1), ')');
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution_50 solution_50_0 = new Solution_50();
      // Undeclared exception!
      try { 
        solution_50_0.maxConsecutiveChar((String) null, (-228), '<');
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Solution_50", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Solution_50 solution_50_0 = new Solution_50();
      // Undeclared exception!
      try { 
        solution_50_0.maxConsecutiveAnswers("L", (-1378));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Solution_50 solution_50_0 = new Solution_50();
      // Undeclared exception!
      try { 
        solution_50_0.maxConsecutiveAnswers((String) null, (-781));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Solution_50", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Solution_50 solution_50_0 = new Solution_50();
      int int0 = solution_50_0.maxConsecutiveChar("pEf_*J;T[])gcUiU", 0, ')');
      assertEquals(1, int0);
  }
}
