/*
 * This file was automatically generated by EvoSuite
 * Mon May 02 10:13:31 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution_190_ESTest extends Solution_190_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution_190 solution_190_0 = new Solution_190();
      // Undeclared exception!
      solution_190_0.reverseStr("!}^{b.yxw]~8%\"", (-2767));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution_190 solution_190_0 = new Solution_190();
      // Undeclared exception!
      try { 
        solution_190_0.reverseStr((String) null, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution_190 solution_190_0 = new Solution_190();
      // Undeclared exception!
      try { 
        solution_190_0.reverseStr("76,G]kCg%.](Y6`", (-43905234));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution_190 solution_190_0 = new Solution_190();
      char[] charArray0 = new char[9];
      // Undeclared exception!
      try { 
        solution_190_0.reverse(charArray0, 2, 80);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution_190 solution_190_0 = new Solution_190();
      char[] charArray0 = new char[9];
      solution_190_0.reverse(charArray0, 0, 0);
      assertEquals(9, charArray0.length);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Solution_190 solution_190_0 = new Solution_190();
      // Undeclared exception!
      try { 
        solution_190_0.reverse((char[]) null, (-43730400), 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Solution_190 solution_190_0 = new Solution_190();
      String string0 = solution_190_0.reverseStr("/`HiB_P0U*PP2:C}", 899);
      assertEquals("}C:2PP*U0P_BiH`/", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Solution_190 solution_190_0 = new Solution_190();
      String string0 = solution_190_0.reverseStr("", 1);
      assertEquals("", string0);
  }
}
